# fly.toml app configuration file generated for whereiscurtis on 2025-04-04T21:35:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whereiscurtis'
primary_region = 'sjc'

[build]
  dockerfile = "Dockerfile"

[env]
  DATABASE_URL = "/mnt/volume/production.sqlite3"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.backup]
    grace_period = "30s"
    interval = "1m"
    method = "get"
    path = "/backup"
    port = 3000
    timeout = "60s"
    type = "http"

[[mounts]]
  destination = "/mnt/volume"
  source = "sqlite3_volume"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1